import { Subject } from "../models/subject";

export const subjects: Subject[] = [
    {
        id: 'geral',
        name: 'Geral',
        description: 'Conhecimentos gerais do dia a dia.',
        topics: ['Geral'],
        theme: {
            icon: 'category',
            accent: 'bg-slate-500',
            border: 'border-slate-200',
            iconBackground: 'bg-slate-50 text-slate -700',
            progress: 'bg-slate-500',
            softBackground: 'bg-slate-50',
            text: 'text-slate-700',
        },
    },
    {
        id: 'math',
        name: 'Matematica',
        description: 'Numeros, operacoes e logica para resolver problemas do dia a dia.',
        topics: ['Aritmetica', 'Calculo mental', 'Logica'],
        theme: {
            icon: 'calculate',
            accent: 'bg-emerald-500',
            border: 'border-emerald-200',
            iconBackground: 'bg-emerald-50 text-emerald-700',
            progress: 'bg-emerald-500',
            softBackground: 'bg-emerald-50',
            text: 'text-emerald-700',
        },
    },
    // {
    //     id: 'science',
    //     name: 'Ciencias',
    //     description: 'Corpo humano, natureza, experimentos e formas de investigar o mundo.',
    //     topics: ['Corpo humano', 'Experimentos', 'Natureza'],
    //     theme: {
    //         icon: 'science',
    //         accent: 'bg-sky-500',
    //         border: 'border-sky-200',
    //         iconBackground: 'bg-sky-50 text-sky-700',
    //         progress: 'bg-sky-500',
    //         softBackground: 'bg-sky-50',
    //         text: 'text-sky-700',
    //     },
    // },
    {
        id: 'history',
        name: 'Historia',
        description: 'Eventos, sociedades e escolhas que ajudam a entender o presente.',
        topics: ['Brasil colonia', 'Cronologia', 'Culturas'],
        theme: {
            icon: 'history_edu',
            accent: 'bg-rose-500',
            border: 'border-rose-200',
            iconBackground: 'bg-rose-50 text-rose-700',
            progress: 'bg-rose-500',
            softBackground: 'bg-rose-50',
            text: 'text-rose-700',
        },
    },
    {
        id: 'geography',
        name: 'Geografia',
        description: 'Mapas, lugares, paisagens e relacoes entre pessoas e territorio.',
        topics: ['Biomas', 'Mapas', 'Clima'],
        theme: {
            icon: 'public',
            accent: 'bg-amber-500',
            border: 'border-amber-200',
            iconBackground: 'bg-amber-50 text-amber-700',
            progress: 'bg-amber-500',
            softBackground: 'bg-amber-50',
            text: 'text-amber-700',
        },
    },
];
